<?php
return array(
    // Common head and page titles
    "global:head_page_title.app" => "!!AppSkeleton",

    // Parts of page
    "global:and" => "and",
    "global:or" => "or",
    "global:from" => "from",
    "global:to" => "to",
    "global:filter_by" => "Filter by",
    "global:no_records_found" => "No records found",
    "global:no_image" => "No image uploaded",
    "global:no_images" => "No images uploaded",
    "global:no_file" => "No file uploaded",
    "global:sure_delete.js" => get_js_safe_string("Are you sure you want to delete record?"),
    "global:pdf.page_num_format" => "{PAGE_NUM} of {PAGE_COUNT}",
    "global:pdf.euro_sign" => "Euro ",

    "global:month_long_1" => "January",
    "global:month_long_2" => "February",
    "global:month_long_3" => "March",
    "global:month_long_4" => "April",
    "global:month_long_5" => "May",
    "global:month_long_6" => "June",
    "global:month_long_7" => "July",
    "global:month_long_8" => "August",
    "global:month_long_9" => "September",
    "global:month_long_10" => "October",
    "global:month_long_11" => "November",
    "global:month_long_12" => "December",

    "global:weekday_short_0" => "Su",
    "global:weekday_short_1" => "Mo",
    "global:weekday_short_2" => "Tu",
    "global:weekday_short_3" => "We",
    "global:weekday_short_4" => "Th",
    "global:weekday_short_5" => "Fr",
    "global:weekday_short_6" => "Sa",

    "global:weekday_long_0" => "Sunday",
    "global:weekday_long_1" => "Monday",
    "global:weekday_long_2" => "Tuesday",
    "global:weekday_long_3" => "Wednesday",
    "global:weekday_long_4" => "Thursday",
    "global:weekday_long_5" => "Friday",
    "global:weekday_long_6" => "Saturday",

    // Titles
    "global:actions" => "Actions",
    "global:id" => "ID",
    "global:date" => "Date",
    "global:created_date" => "Creation date",
    "global:updated_date" => "Modification date",
    "global:title" => "Title",
    "global:body" => "Body",
    "global:text" => "Text",
    "global:notes" => "Notes",
    "global:description" => "Description",
    "global:extra_info" => "Extra info",
    "global:thumbnail" => "Thumbnail",
    "global:image" => "Image",
    "global:file" => "File",
    "global:first_name" => "First Name",
    "global:last_name" => "Last Name",
    "global:name" => "Name",
    "global:full_name" => "Full Name",
    "global:login" => "Login",
    "global:password" => "Password",
    "global:password_confirm" => "Confirm password",
    "global:role" => "Role",
    "global:is_confirmed" => "Confirmed?",
    "global:is_active" => "Active?",
    "global:should_remember" => "Remember me",
    "global:accept_agreement" => "I accept",
    "global:company_name" => "Company",
    "global:company_type" => "Type",
    "global:company_position" => "Position",
    "global:piva" => "VAT No.",
    "global:codice_fiscale" => "Fiscal code",
    "global:email" => "Email",
    "global:website" => "Website",
    "global:country" => "Country",
    "global:province" => "Province",
    "global:city" => "City",
    "global:address" => "Address",
    "global:zip" => "ZIP",
    "global:phone" => "Phone",
    "global:phone_short" => "Tel.",
    "global:fax" => "Fax",
    "global:message_text" => "Message",
    "global:keywords" => "Keywords",
    "global:bank_name" => "Bank",
    "global:bank_office_name" => "Branch",
    "global:status" => "Status",
    "global:price" => "Price",
    "global:current_image" => "Current image",
    "global:current_images" => "Current images",
    "global:upload_new_image" => "Upload new image",
    "global:current_file" => "Current file",
    "global:upload_new_file" => "Upload new file",

    // Link/button titles
    "global:view" => "View",
    "global:view_short" => "View",
    "global:edit" => "Edit",
    "global:edit_short" => "Edit",
    "global:add" => "Add",
    "global:add_short" => "Add",
    "global:delete" => "Delete",
    "global:delete_short" => "Del",
    "global:select" => "Select",
    "global:back" => "Back",
    "global:send" => "Send",
    "global:update" => "Update",
    "global:save" => "Save",
    "global:save_and_send" => "Save and Send",
    "global:filter" => "Filter",
    "global:show" => "Show",
    "global:show_all" => "Show all",
    "global:login" => "Login",
    "global:logout" => "Logout",
    "global:signup" => "Signup",
    "global:confirm" => "Confirm",
    "global:unconfirm" => "Undo confirm",
    "global:deactivate" => "Deactivate",
    "global:activate" => "Activate",
    "global:proceed" => "Proceed",
    "global:move_up" => "Up",
    "global:move_down" => "Down",
    "global:move_left" => "Left",
    "global:move_right" => "Right",
    "global:previous" => "Previous",
    "global:next" => "Next",
    "global:accept" => "Accept",
    "global:reject" => "Reject",
    "global:assign" => "Assign",
    "global:resume" => "Resume",
    "global:suspend" => "Suspend",
    "global:finish" => "Finish",
    "global:done" => "Done",
    "global:generate" => "Generate",

    "global:delete_image" => "Delete image",
    "global:delete_file" => "Delete file",
    "global:activate_deactivate" => "Activate/Deactivate",
    "global:save_and_products" => "Save and View products",

    // Users
    "global:user.add" => "Add user",
    "global:user.back_to_list" => "Back to users list",

    "global:user.login" => "Login",
    "global:user.role" => "Role",
    "global:user.password" => "Password",
    "global:user.password_confirm" => "Confirm password",
    "global:user.first_name" => "First Name",
    "global:user.last_name" => "Last Name",
    "global:user.email" => "Email",
    "global:user.extra_info" => "Extra info",
    "global:user.is_confirmed" => "Confirmed?",
    "global:user.is_active" => "Active?",
    "global:user.accept_agreement" => "I Accept",
    "global:user.should_remember" => "Remember me", 
    "global:user.date_created" => "Creation date",
    "global:user.name" => "Name",

    // Contact info
    "global:contact_info.first_name" => "First Name",
    "global:contact_info.last_name" => "Last Name",
    "global:contact_info.email" => "Email",
    "global:contact_info.phone" => "Phone",
    "global:contact_info.company_name" => "Company",
    "global:contact_info.city" => "City",
    "global:contact_info.address" => "Address",
    "global:contact_info.fax" => "Fax",
    "global:contact_info.message_text" => "Message",
    "global:contact_info.security_code" => "Security code",
    
    // News articles
    "global:news_article.add" => "Add news article",
    "global:news_article.back_to_list" => "Back to news articles",

    "global:news_article.created_date" => "Date",
    "global:news_article.title" => "Title",
    "global:news_article.body" => "Body",
    "global:news_article.image" => "Image",
    "global:news_article.file" => "File",
    "global:news_article.current_image" => "Current image",
    "global:news_article.upload_new_image" => "Upload new image",
    "global:news_article.current_file" => "Current file",
    "global:news_article.upload_new_file" => "Upload new file",
    "global:news_article.text" => "Text",

    "global:news_article.rss_feed.title" => "News rss feed",

    // Newsletters and newsletter categories
    "global:newsletter.add" => "Create newsletter",
    "global:newsletter.back_to_list" => "Back to newsletters",

    "global:newsletter.category" => "Category",
    "global:newsletter.sent_date" => "Sending date",
    "global:newsletter.title" => "Title",
    "global:newsletter.body" => "Body",
    "global:newsletter.image" => "Image",
    "global:newsletter.file" => "File",
    "global:newsletter.current_image" => "Current image",
    "global:newsletter.upload_new_image" => "Upload new image",
    "global:newsletter.current_file" => "Current file",
    "global:newsletter.upload_new_file" => "Upload new file",
    "global:newsletter.text" => "Text",

    "global:newsletter_category.add" => "Add newsletter category",
    "global:newsletter_category.back_to_list" => "Back to newsletter categories",

    "global:newsletter_category.name" => "Name",
    "global:newsletter_category.is_active" => "Active?",
    "global:newsletter_category.is_subscribed" => "Subscribed?",
    "global:newsletter_category.name.full" => "Category",

    // Categories
    "global:category1.add" => "Add category1",

    "global:category1.title" => "Category1",
    "global:category1.name" => "Name",
    
    "global:category2.add" => "Add category2",

    "global:category2.title" => "Category2",
    "global:category2.name" => "Name",

    "global:category3.add" => "Add category3",

    "global:category3.title" => "Category3",
    "global:category3.name" => "Name",

    // Products
    "global:product.add" => "Add product",
    "global:product.back_to_list" => "Back to products",
    "global:product.download_pdf" => "Download PDF",

    "global:product.category1" => "Category1",
    "global:product.category2" => "Category2",
    "global:product.category3" => "Category3",
    "global:product.name" => "Name",
    "global:product.description" => "Description",
    "global:product.price" => "Price",
    "global:product.category" => "Category",
    "global:product.keywords" => "Keywords",
    "global:product.primary_thumbnail_image" => "Primary image",
    "global:product.current_primary_image" => "Current primary image",
    "global:product.upload_new_primary_image" => "Upload new primary image",
    "global:product.upload_new_image" => "Upload new image",
);
?>