<?php
return array(
    // Common head and page titles
    "global:head_page_title.app" => "!!AppSkeleton",

    // Parts of page
    "global:sure_delete" => "Sei sicuro di voler cancellare l\\'informazione?",
    "global:and" => "e",
    "global:or" => "o",
    "global:from" => "dal",
    "global:to" => "al",
    "global:filter_by" => "Filtra per",
    "global:no_records_found" => "Non sono stati trovati dati",
    "global:no_image" => "No immagine",
    "global:no_file" => "No file",

    // Titles
    "global:actions" => "Azioni",
    "global:id" => "ID",
    "global:date" => "Data",
    "global:date_created" => "Data Creato",
    "global:title" => "Titolo",
    "global:body" => "Corpo",
    "global:text" => "Testo",
    "global:notes" => "Note",
    "global:description" => "Descrizione",
    "global:extra_info" => "Maggiori informazioni",
    "global:image" => "Immagine",
    "global:file" => "File",
    "global:first_name" => "Nome",
    "global:last_name" => "Cognome",
    "global:name" => "Nome",
    "global:full_name" => "Nome",
    "global:login" => "Login",
    "global:password" => "Password",
    "global:password_confirm" => "Conferma password",
    "global:role" => "Ruolo",
    "global:is_confirmed" => "Confermato?",
    "global:is_active" => "Attivo?",
    "global:should_remember" => "Ricorda dati accesso",
    "global:accept_agreement" => "Accetto",
    "global:company_name" => "Ragione Sociale",
    "global:company_type" => "Forma Societaria",
    "global:company_position" => "Ruolo aziendale",
    "global:piva" => "Partità IVA",
    "global:codice_fiscale" => "Codice Fiscale",
    "global:email" => "Email",
    "global:website" => "Sito Web",
    "global:country" => "Nazione",
    "global:province" => "Provincia",
    "global:city" => "Città",
    "global:address" => "Indirizzo",
    "global:zip" => "CAP",
    "global:phone" => "Telefono",
    "global:phone_short" => "Tel.",
    "global:fax" => "Fax",
    "global:message_text" => "Messaggio",
    "global:keywords" => "Parole Chiavi",
    "global:bank_name" => "Banca",
    "global:bank_office_name" => "Filiale",
    "global:status" => "Stato",
    "global:price" => "Prezzo",
    "global:current_image" => "Immagine corrente",
    "global:upload_new_image" => "Carica nuova immagine",
    "global:current_file" => "File corrente",
    "global:upload_new_file" => "Carica nuovo file",
    "global:category" => "Categoria",
    "global:category1" => "Categoria1",
    "global:category2" => "Categoria2",
    "global:category3" => "Categoria3",

    // Link/button titles
    "global:view" => "Visualizza",
    "global:view_short" => "Vis",
    "global:edit" => "Modifica",
    "global:edit_short" => "Mod",
    "global:add" => "Aggiungi",
    "global:add_short" => "Agg",
    "global:delete" => "Cancella",
    "global:delete_short" => "Canc",
    "global:select" => "Seleziona",
    "global:back" => "Indietro",
    "global:send" => "Invia",
    "global:save" => "Salva",
    "global:save_and_send" => "Salva e Invia",
    "global:filter" => "Filtra",
    "global:show" => "Invio",
    "global:show_all" => "Mostra Tutto",
    "global:login" => "Login",
    "global:logout" => "Logout",
    "global:signup" => "Iscriviti",
    "global:confirm" => "Conferma",
    "global:unconfirm" => "Rimuovi conferma",
    "global:deactivate" => "Disattiva",
    "global:activate" => "Activate",
    "global:proceed" => "Procedi",
    "global:move_up" => "Su",
    "global:move_down" => "Giù",
    "global:move_left" => "Sinistro",
    "global:move_right" => "Destro",
    "global:previous" => "Precedente",
    "global:next" => "Prossimo",
    "global:accept" => "Accetta",
    "global:reject" => "Rifiuta",
    "global:assign" => "Assegna",
    "global:resume" => "Riattiva",
    "global:suspend" => "Sospendi",
    "global:finish" => "Fine",
    "global:done" => "Eseguito",
    "global:generate" => "Genera",

    "global:delete_image" => "Cancella immagine",
    "global:delete_file" => "Cancella file",
    "global:activate_deactivate" => "!!Activate/Deactivate",

    "global:view_all_news" => "Tutte le News",
    "global:add_news_article" => "Aggiungi notizia",
    "global:back_to_news_articles" => "!!Torna alla lista ... notizie",
    
    "global:add_user" => "Aggiungi utente",
    "global:back_to_users" => "!!Torna alla lista degli utenti",
    "global:back_to_user_view" => "!!Torna al dettaglio utente",

    "global:add_category1" => "Aggiungi categoria1",

    "global:add_category2" => "Aggiungi categoria2",
    
    "global:add_category3" => "Aggiungi categoria3",
    
    "global:add_product" => "Aggiungi prodotto",
    "global:back_to_products" => "!!Torna alla lista ... prodotti",

    "global:add_newsletter" => "!!Aggiungi newsletter",
    "global:back_to_newsletters" => "!!Torna alla lista ... newsletters",

    "global:add_newsletter_category" => "!!Aggiungi newsletter categoria",
    "global:back_to_newsletter_categories" => "!!Torna alla lista ... newsletter categorie",
);
?>