<?php
return array(
    // Common head and page titles
    "global:head_page_title.app" => "!!AppSkeleton",

    // Parts of page
    "global:and" => "e",
    "global:or" => "o",
    "global:from" => "da",
    "global:to" => "a",
    "global:filter_by" => "Filtra per",
    "global:no_records_found" => "Non sono stati trovati dati",
    "global:no_image" => "Immagine non presente",
    "global:no_images" => "Nessuna immagine",
    "global:no_file" => "Nessun file",
    "global:sure_delete.js" => get_js_safe_string("Sei sicuro di voler cancellare l'informazione?"),
    "global:pdf.page_num_format" => "{PAGE_NUM} di {PAGE_COUNT}",
    "global:pdf.euro_sign" => "Euro ",

    "global:month_long_1" => "Gennaio",
    "global:month_long_2" => "Febbraio",
    "global:month_long_3" => "Marzo",
    "global:month_long_4" => "Aprile",
    "global:month_long_5" => "Maggio",
    "global:month_long_6" => "Giugno",
    "global:month_long_7" => "Luglio",
    "global:month_long_8" => "Agosto",
    "global:month_long_9" => "Settembre",
    "global:month_long_10" => "Ottobre",
    "global:month_long_11" => "Novembre",
    "global:month_long_12" => "Dicembre",

    "global:weekday_short_0" => "Do",
    "global:weekday_short_1" => "Lu",
    "global:weekday_short_2" => "Ma",
    "global:weekday_short_3" => "Me",
    "global:weekday_short_4" => "Gi",
    "global:weekday_short_5" => "Ve",
    "global:weekday_short_6" => "Sa",

    "global:weekday_long_0" => "Domenica",
    "global:weekday_long_1" => "Lunedì",
    "global:weekday_long_2" => "Martedì",
    "global:weekday_long_3" => "Mercoledì",
    "global:weekday_long_4" => "Giovedì",
    "global:weekday_long_5" => "Venerdì",
    "global:weekday_long_6" => "Sabato",

    // Titles
    "global:actions" => "Azioni",
    "global:id" => "ID",
    "global:date" => "Data",
    "global:created_date" => "Data di creazione",
    "global:updated_date" => "Data di modifica",
    "global:title" => "Titolo",
    "global:body" => "Corpo",
    "global:text" => "Testo",
    "global:notes" => "Note",
    "global:description" => "Descrizione",
    "global:extra_info" => "Maggiori informazioni",
    "global:thumbnail" => "Anteprima",
    "global:image" => "Immagine",
    "global:file" => "File",
    "global:first_name" => "Nome",
    "global:last_name" => "Cognome",
    "global:name" => "Nome",
    "global:full_name" => "Nome",
    "global:login" => "Login",
    "global:password" => "Password",
    "global:password_confirm" => "Conferma password",
    "global:role" => "Ruolo",
    "global:is_confirmed" => "Confermato?",
    "global:is_active" => "Attivo?",
    "global:should_remember" => "Ricorda dati d'accesso",
    "global:accept_agreement" => "Accetto",
    "global:company_name" => "Ragione Sociale",
    "global:company_type" => "Forma Societaria",
    "global:company_position" => "Ruolo aziendale",
    "global:piva" => "Partità IVA",
    "global:codice_fiscale" => "Codice Fiscale",
    "global:email" => "Email",
    "global:website" => "Sito Web",
    "global:country" => "Nazione",
    "global:province" => "Provincia",
    "global:city" => "Città",
    "global:address" => "Indirizzo",
    "global:zip" => "CAP",
    "global:phone" => "Telefono",
    "global:phone_short" => "Tel.",
    "global:fax" => "Fax",
    "global:message_text" => "Messaggio",
    "global:keywords" => "Parole Chiavi",
    "global:bank_name" => "Banca",
    "global:bank_office_name" => "Filiale",
    "global:status" => "Stato",
    "global:price" => "Prezzo",
    "global:current_image" => "Immagine corrente",
    "global:current_images" => "Immagini correnti",
    "global:upload_new_image" => "Carica nuova immagine",
    "global:current_file" => "File corrente",
    "global:upload_new_file" => "Carica nuovo file",

    // Link/button titles
    "global:view" => "Visualizza",
    "global:view_short" => "Vis",
    "global:edit" => "Modifica",
    "global:edit_short" => "Mod",
    "global:add" => "Aggiungi",
    "global:add_short" => "Agg",
    "global:delete" => "Cancella",
    "global:delete_short" => "Canc",
    "global:select" => "Seleziona",
    "global:back" => "Indietro",
    "global:send" => "Invia",
    "global:update" => "Aggiorna",
    "global:save" => "Salva",
    "global:save_and_send" => "Salva e Invia",
    "global:filter" => "Filtra",
    "global:show" => "Invio",
    "global:show_all" => "Mostra Tutto",
    "global:login" => "Login",
    "global:logout" => "Logout",
    "global:signup" => "Iscriviti",
    "global:confirm" => "Conferma",
    "global:unconfirm" => "Rimuovi conferma",
    "global:deactivate" => "Disattiva",
    "global:activate" => "Attiva",
    "global:proceed" => "Procedi",
    "global:move_up" => "Su",
    "global:move_down" => "Giù",
    "global:move_left" => "Sinistro",
    "global:move_right" => "Destro",
    "global:previous" => "Precedente",
    "global:next" => "Prossimo",
    "global:accept" => "Accetta",
    "global:reject" => "Rifiuta",
    "global:assign" => "Assegna",
    "global:resume" => "Riattiva",
    "global:suspend" => "Sospendi",
    "global:finish" => "Fine",
    "global:done" => "Eseguito",
    "global:generate" => "Genera",

    "global:delete_image" => "Cancella immagine",
    "global:delete_file" => "Cancella file",
    "global:activate_deactivate" => "Attiva/Disattiva",
    "global:save_and_products" => "Salva e Visualizza prodotti",

    // Users
    "global:user.add" => "Aggiungi utente",
    "global:user.back_to_list" => "Torna all'elenco utenti",

    "global:user.login" => "Login",
    "global:user.role" => "Ruolo",
    "global:user.password" => "Password",
    "global:user.password_confirm" => "Conferma password",
    "global:user.first_name" => "Nome",
    "global:user.last_name" => "Cognome",
    "global:user.email" => "Email",
    "global:user.extra_info" => "Maggiori informazioni",
    "global:user.is_confirmed" => "Confermato?",
    "global:user.is_active" => "Attivo?",
    "global:user.accept_agreement" => "Accetto",
    "global:user.should_remember" => "Ricorda dati d'accesso",
    "global:user.date_created" => "Data di creazione",
    "global:user.name" => "Nome",

    // Contact info
    "global:contact_info.first_name" => "Nome",
    "global:contact_info.last_name" => "Cognome",
    "global:contact_info.email" => "Email",
    "global:contact_info.phone" => "Telefono",
    "global:contact_info.company_name" => "Azienda",
    "global:contact_info.city" => "Città",
    "global:contact_info.address" => "Indirizzo",
    "global:contact_info.fax" => "Fax",
    "global:contact_info.message_text" => "Messaggio",
    "global:contact_info.security_code" => "Codice di sicurezza",

    // News articles
    "global:news_article.add" => "Aggiungi news",
    "global:news_article.back_to_list" => "Torna all'elenco news",

    "global:news_article.created_date" => "Data",
    "global:news_article.title" => "Titolo",
    "global:news_article.body" => "Corpo",
    "global:news_article.image" => "Immagine",
    "global:news_article.file" => "File",
    "global:news_article.current_image" => "Immagine corrente",
    "global:news_article.upload_new_image" => "Carica nuova immagine",
    "global:news_article.current_file" => "File corrente",
    "global:news_article.upload_new_file" => "Carica nuovo file",
    "global:news_article.text" => "Text",

    "global:news_article.rss_feed.title" => "News rss feed",

    // Newsletters and newsletter categories
    "global:newsletter.add" => "Crea newsletter",
    "global:newsletter.back_to_list" => "Torna all'elenco newsletter",

    "global:newsletter.category" => "Categoria",
    "global:newsletter.sent_date" => "Data di invio",
    "global:newsletter.title" => "Titolo",
    "global:newsletter.body" => "Testo",
    "global:newsletter.image" => "Immagine",
    "global:newsletter.file" => "File",
    "global:newsletter.current_image" => "Immagine corrente",
    "global:newsletter.upload_new_image" => "Carica nuova immagine",
    "global:newsletter.current_file" => "File corrente",
    "global:newsletter.upload_new_file" => "Carica nuovo file",
    "global:newsletter.text" => "Testo",

    "global:newsletter_category.add" => "Aggiungi categoria newsletter",
    "global:newsletter_category.back_to_list" => "Torna all'elenco delle categorie newsletter",

    "global:newsletter_category.name" => "Nome",
    "global:newsletter_category.is_active" => "Attivo?",
    "global:newsletter_category.is_subscribed" => "Iscritto?",
    "global:newsletter_category.name.full" => "Categoria",

    // Categories
    "global:category1.add" => "Aggiungi categoria1",

    "global:category1.title" => "Categoria1",
    "global:category1.name" => "Name",

    "global:category2.add" => "Aggiungi categoria2",

    "global:category2.title" => "Categoria2",
    "global:category2.name" => "Name",

    "global:category3.add" => "Aggiungi categoria3",

    "global:category3.title" => "Categoria3",
    "global:category3.name" => "Name",

    // Products
    "global:product.add" => "Aggiungi prodotto",
    "global:product.back_to_list" => "Torna all'elenco prodotti",
    "global:product.download_pdf" => "Scarica PDF",

    "global:product.category1" => "Categoria1",
    "global:product.category2" => "Categoria2",
    "global:product.category3" => "Categoria3",
    "global:product.name" => "Nome",
    "global:product.description" => "Descrizione",
    "global:product.price" => "Prezzo",
    "global:product.category" => "Categoria",
    "global:product.keywords" => "Parole Chiave",
    "global:product.primary_thumbnail_image" => "Immagine primaria",
    "global:product.current_primary_image" => "Immagine primaria corrente",
    "global:product.upload_new_primary_image" => "Carica nuova immagine primaria",
    "global:product.upload_new_image" => "Carica nuova immagine",
);
?>