<?php
return array(
    // Common head and page titles
    "global:head_page_title.app" => "!!AppSkeleton",

    // Parts of page
    "global:sure_delete.js" => get_js_safe_string("Are you sure you want to delete record?"),
    "global:and" => "and",
    "global:or" => "or",
    "global:from" => "from",
    "global:to" => "to",
    "global:filter_by" => "Filter by",
    "global:no_records_found" => "No records found",
    "global:no_image" => "No image uploaded",
    "global:no_file" => "No file uploaded",

    // Titles
    "global:actions" => "Actions",
    "global:id" => "ID",
    "global:date" => "Date",
    "global:date_created" => "Creation date",
    "global:title" => "Title",
    "global:body" => "Body",
    "global:text" => "Text",
    "global:notes" => "Notes",
    "global:description" => "Description",
    "global:extra_info" => "Extra info",
    "global:image" => "Image",
    "global:file" => "File",
    "global:first_name" => "First Name",
    "global:last_name" => "Last Name",
    "global:name" => "Name",
    "global:full_name" => "Full Name",
    "global:login" => "Login",
    "global:password" => "Password",
    "global:password_confirm" => "Confirm password",
    "global:role" => "Role",
    "global:is_confirmed" => "Confirmed?",
    "global:is_active" => "Active?",
    "global:should_remember" => "Remember me",
    "global:accept_agreement" => "I accept",
    "global:company_name" => "Company",
    "global:company_type" => "Type",
    "global:company_position" => "Position",
    "global:piva" => "VAT No.",
    "global:codice_fiscale" => "Fiscal code",
    "global:email" => "Email",
    "global:website" => "Website",
    "global:country" => "Country",
    "global:province" => "Province",
    "global:city" => "City",
    "global:address" => "Address",
    "global:zip" => "ZIP",
    "global:phone" => "Phone",
    "global:phone_short" => "Tel.",
    "global:fax" => "Fax",
    "global:message_text" => "Message",
    "global:keywords" => "Keywords",
    "global:bank_name" => "Bank",
    "global:bank_office_name" => "Branch",
    "global:status" => "Status",
    "global:price" => "Price",
    "global:current_image" => "Current image",
    "global:upload_new_image" => "Upload new image",
    "global:current_file" => "Current file",
    "global:upload_new_file" => "Upload new file",
    "global:category" => "Category",
    "global:category1" => "Category1",
    "global:category2" => "Category2",
    "global:category3" => "Category3",

    // Link/button titles
    "global:view" => "View",
    "global:view_short" => "View",
    "global:edit" => "Edit",
    "global:edit_short" => "Edit",
    "global:add" => "Add",
    "global:add_short" => "Add",
    "global:delete" => "Delete",
    "global:delete_short" => "Del",
    "global:select" => "Select",
    "global:back" => "Back",
    "global:send" => "Send",
    "global:save" => "Save",
    "global:save_and_send" => "Save and Send",
    "global:filter" => "Filter",
    "global:show" => "Show",
    "global:show_all" => "Show all",
    "global:login" => "Login",
    "global:logout" => "Logout",
    "global:signup" => "Signup",
    "global:confirm" => "Confirm",
    "global:unconfirm" => "Undo confirm",
    "global:deactivate" => "Deactivate",
    "global:activate" => "Activate",
    "global:proceed" => "Proceed",
    "global:move_up" => "Up",
    "global:move_down" => "Down",
    "global:move_left" => "Left",
    "global:move_right" => "Right",
    "global:previous" => "Previous",
    "global:next" => "Next",
    "global:accept" => "Accept",
    "global:reject" => "Reject",
    "global:assign" => "Assign",
    "global:resume" => "Resume",
    "global:suspend" => "Suspend",
    "global:finish" => "Finish",
    "global:done" => "Done",
    "global:generate" => "Generate",

    "global:delete_image" => "Delete image",
    "global:delete_file" => "Delete file",
    "global:activate_deactivate" => "Activate/Deactivate",

    "global:view_all_news" => "View all news",
    "global:add_news_article" => "Add news article",
    "global:back_to_news_articles" => "Back to news articles",

    "global:add_user" => "Add user",
    "global:back_to_users" => "Back to users",
    "global:back_to_user_view" => "Back to user view",

    "global:add_category1" => "Add category1",

    "global:add_category2" => "Add category2",

    "global:add_category3" => "Add category3",

    "global:add_product" => "Add product",
    "global:back_to_products" => "Back to products",

    "global:add_newsletter" => "Add newsletter",
    "global:back_to_newsletters" => "Back to newsletters",

    "global:add_newsletter_category" => "Add newsletter category",
    "global:back_to_newsletter_categories" => "Back to newsletter categories",
);
?>