<?php
return array(
    // Common head and page titles
    "lang:head_page_title.app" => "!!AppSkeleton",

    // Titles
    "lang:actions" => "Actions",
    "lang:id" => "ID",
    "lang:date" => "Date",
    "lang:date_created" => "Creation date",
    "lang:title" => "Title",
    "lang:body" => "Body",
    "lang:text" => "Text",
    "lang:notes" => "Notes",
    "lang:description" => "Description",
    "lang:extra_info" => "Extra info",
    "lang:image" => "Image",
    "lang:file" => "File",
    "lang:first_name" => "First Name",
    "lang:last_name" => "Last Name",
    "lang:name" => "Name",
    "lang:full_name" => "Full Name",
    "lang:login" => "Login",
    "lang:password" => "Password",
    "lang:password_confirm" => "Confirm password",
    "lang:role" => "Role",
    "lang:is_confirmed" => "Confirmed?",
    "lang:is_active" => "Active?",
    "lang:company_name" => "Company",
    "lang:company_type" => "Type",
    "lang:company_position" => "Position",
    "lang:piva" => "VAT No.",
    "lang:codice_fiscale" => "Fiscal code",
    "lang:email" => "Email",
    "lang:website" => "Website",
    "lang:country" => "Country",
    "lang:province" => "Province",
    "lang:city" => "City",
    "lang:address" => "Address",
    "lang:zip" => "ZIP",
    "lang:phone" => "Phone",
    "lang:phone_short" => "Tel.",
    "lang:fax" => "Fax",
    "lang:message_text" => "Message",
    "lang:keywords" => "Keywords",
    "lang:bank_name" => "Bank",
    "lang:bank_office_name" => "Branch",
    "lang:status" => "Status",
    "lang:price" => "Price",
    "lang:current_image" => "Current image",
    "lang:upload_new_image" => "Upload new image",
    "lang:current_file" => "Current file",
    "lang:upload_new_file" => "Upload new file",
    "lang:category" => "Category",
    "lang:category1" => "Category1",
    "lang:category2" => "Category2",
    "lang:category3" => "Category3",

    // Link/button titles
    "lang:view" => "View",
    "lang:view_short" => "View",
    "lang:edit" => "Edit",
    "lang:edit_short" => "Edit",
    "lang:add" => "Add",
    "lang:add_short" => "Add",
    "lang:delete" => "Delete",
    "lang:delete_short" => "Del",
    "lang:select" => "Select",
    "lang:back" => "Back",
    "lang:send" => "Send",
    "lang:save" => "Save",
    "lang:filter" => "Filter",
    "lang:show" => "Show",
    "lang:show_all" => "Show all",
    "lang:login" => "Login",
    "lang:logout" => "Logout",
    "lang:signup" => "Signup",
    "lang:confirm" => "Confirm",
    "lang:unconfirm" => "Undo confirm",
    "lang:deactivate" => "Deactivate",
    "lang:activate" => "Activate",
    "lang:proceed" => "Proceed",
    "lang:move_up" => "Up",
    "lang:move_down" => "Down",
    "lang:move_left" => "Left",
    "lang:move_right" => "Right",
    "lang:accept" => "Accept",
    "lang:reject" => "Reject",
    "lang:delete_image" => "Delete image",
    "lang:delete_file" => "Delete file",

    // Parts of page
    "lang:sure_delete" => "Are you sure you want to delete record?",
    "lang:and" => "e",
    "lang:or" => "o",
    "lang:from" => "from",
    "lang:to" => "to",
    "lang:filter_by" => "Filter by",
    "lang:no_records_found" => "No records found",
    "lang:no_image" => "No image uploaded",
    "lang:no_file" => "No file uploaded",
);
?>