<?php
return array(
    // Common head and page titles
    "lang:head_page_title.app" => "!!AppSkeleton",

    // Titles
    "lang:actions" => "Azioni",
    "lang:id" => "ID",
    "lang:date" => "Data",
    "lang:date_created" => "Data Creato",
    "lang:title" => "Titolo",
    "lang:body" => "Corpo",
    "lang:text" => "Testo",
    "lang:notes" => "Note",
    "lang:description" => "Descrizione",
    "lang:extra_info" => "Maggiori informazioni",
    "lang:image" => "Immagine",
    "lang:file" => "File",
    "lang:first_name" => "Nome",
    "lang:last_name" => "Cognome",
    "lang:name" => "Nome",
    "lang:full_name" => "Nome",
    "lang:login" => "Login",
    "lang:password" => "Password",
    "lang:password_confirm" => "Conferma password",
    "lang:role" => "Ruolo",
    "lang:is_confirmed" => "Confermato?",
    "lang:is_active" => "Attivo?",
    "lang:company_name" => "Ragione Sociale",
    "lang:company_type" => "Forma Societaria",
    "lang:company_position" => "Ruolo aziendale",
    "lang:piva" => "Partità IVA",
    "lang:codice_fiscale" => "Codice Fiscale",
    "lang:email" => "Email",
    "lang:website" => "Sito Web",
    "lang:country" => "Nazione",
    "lang:province" => "Provincia",
    "lang:city" => "Città",
    "lang:address" => "Indirizzo",
    "lang:zip" => "CAP",
    "lang:phone" => "Telefono",
    "lang:phone_short" => "Tel.",
    "lang:fax" => "Fax",
    "lang:message_text" => "Messaggio",
    "lang:keywords" => "Parole Chiavi",
    "lang:bank_name" => "Banca",
    "lang:bank_office_name" => "Filiale",
    "lang:status" => "Stato",
    "lang:price" => "Prezzo",
    "lang:current_image" => "Immagine corrente",
    "lang:upload_new_image" => "Carica nuova immagine",
    "lang:current_file" => "File corrente",
    "lang:upload_new_file" => "Carica nuovo file",
    "lang:category" => "Categoria",
    "lang:category1" => "Categoria1",
    "lang:category2" => "Categoria2",
    "lang:category3" => "Categoria3",

    // Link/button titles
    "lang:view" => "Visualizza",
    "lang:view_short" => "Vis",
    "lang:edit" => "Modifica",
    "lang:edit_short" => "Mod",
    "lang:add" => "Aggiungi",
    "lang:add_short" => "Agg",
    "lang:delete" => "Cancella",
    "lang:delete_short" => "Canc",
    "lang:select" => "Seleziona",
    "lang:back" => "Indietro",
    "lang:send" => "Invia",
    "lang:save" => "Salva",
    "lang:filter" => "Filtra",
    "lang:show" => "Invio",
    "lang:show_all" => "Mostra Tutto",
    "lang:login" => "Login",
    "lang:logout" => "Logout",
    "lang:signup" => "Iscriviti",
    "lang:confirm" => "Conferma",
    "lang:unconfirm" => "Rimuovi conferma",
    "lang:deactivate" => "Disattiva",
    "lang:activate" => "Activate",
    "lang:proceed" => "Procedi",
    "lang:move_up" => "Su",
    "lang:move_down" => "Giù",
    "lang:move_left" => "Sinistro",
    "lang:move_right" => "Destro",
    "lang:accept" => "Accetta",
    "lang:reject" => "Rifiuta",
    "lang:delete_image" => "Cancella immagine",
    "lang:delete_file" => "Cancella file",

    // Parts of page
    "lang:sure_delete" => "Sei sicuro di voler cancellare l\\'informazione?",
    "lang:and" => "e",
    "lang:or" => "o",
    "lang:from" => "dal",
    "lang:to" => "al",
    "lang:filter_by" => "Filtra per",
    "lang:no_records_found" => "Non sono stati trovati dati",
    "lang:no_image" => "No immagine",
    "lang:no_file" => "No file",

    "lang:copyright" => "Copyright", 
);
?>